"""e-CAC provider protocol."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class EcacProvider(Protocol):
    async def get_tax_status(self, subject) -> dict: ...
    async def get_pgdas(self, subject, period: str) -> dict: ...
    async def generate_das(self, subject, period: str) -> dict: ...
    async def get_dctfweb(self, subject, period: str) -> dict: ...
    async def get_mailbox_messages(self, subject) -> list[dict]: ...
    async def get_certidao_status(self, subject) -> dict: ...
    async def get_procuracoes(self, subject) -> list[dict]: ...
