"""add_chat_tables

Revision ID: 68c375818212
Revises: 43813716b407
Create Date: 2026-04-27 16:43:06.911668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '68c375818212'
down_revision: Union[str, None] = '43813716b407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Session title or name'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='Number of messages in this session'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant identifier for data isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_table('token_usage_logs',
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='Number of input tokens consumed'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='Number of output tokens generated'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='AI model used (e.g., claude-3-5-haiku-20241022)'),
    sa.Column('endpoint', sa.String(length=100), nullable=False, comment='API endpoint that generated the usage'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant identifier for data isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_logs_id'), 'token_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_tenant_id'), 'token_usage_logs', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Message unique identifier'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Reference to parent chat session'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Message role: user or assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='Number of tokens used for this message'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Message creation timestamp'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               comment='Vector embedding for semantic search (1024 dimensions - Voyage AI voyage-2)',
               existing_comment='Vector embedding for semantic search (1536 dimensions)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               comment='Vector embedding for semantic search (1536 dimensions)',
               existing_comment='Vector embedding for semantic search (1024 dimensions - Voyage AI voyage-2)',
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_token_usage_logs_tenant_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_id'), table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
