"""add_analytics_tables

Revision ID: d9e4ace766be
Revises: 68c375818212
Create Date: 2026-04-27 16:59:40.596282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e4ace766be'
down_revision: Union[str, None] = '68c375818212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage_metrics',
    sa.Column('date', sa.Date(), nullable=False, comment='Date for which metrics are aggregated'),
    sa.Column('total_sessions', sa.Integer(), nullable=False, comment='Total chat sessions created on this date'),
    sa.Column('total_messages', sa.Integer(), nullable=False, comment='Total chat messages sent on this date'),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False, comment='Total input tokens consumed on this date'),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False, comment='Total output tokens generated on this date'),
    sa.Column('total_documents', sa.Integer(), nullable=False, comment='Total documents ingested on this date'),
    sa.Column('total_chunks', sa.Integer(), nullable=False, comment='Total document chunks created on this date'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant identifier for data isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_daily_metrics_tenant_date')
    )
    op.create_index(op.f('ix_daily_usage_metrics_date'), 'daily_usage_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_usage_metrics_id'), 'daily_usage_metrics', ['id'], unique=False)
    op.create_index('ix_daily_usage_metrics_tenant_date', 'daily_usage_metrics', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_usage_metrics_tenant_id'), 'daily_usage_metrics', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_usage_metrics_tenant_id'), table_name='daily_usage_metrics')
    op.drop_index('ix_daily_usage_metrics_tenant_date', table_name='daily_usage_metrics')
    op.drop_index(op.f('ix_daily_usage_metrics_id'), table_name='daily_usage_metrics')
    op.drop_index(op.f('ix_daily_usage_metrics_date'), table_name='daily_usage_metrics')
    op.drop_table('daily_usage_metrics')
    # ### end Alembic commands ###
