"""Provider protocol for NFS-e operations."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class InvoiceProvider(Protocol):
    """Interface that every NFS-e provider must implement."""

    async def validate_issuer(self, issuer) -> dict: ...
    async def issue_nfse(self, invoice) -> dict: ...
    async def get_status(self, invoice) -> dict: ...
    async def cancel_nfse(self, invoice, reason: str) -> dict: ...
    async def fetch_xml(self, invoice) -> bytes: ...
    async def fetch_pdf(self, invoice) -> bytes: ...
